import { parseArchitectureDocument, type ArchitectureDocument } from "@axon/diagram-schema";
import { describe, expect, it } from "vitest";

import {
  canvasStateToDocument,
  computeArchitectureAwareLayout,
  createUniqueEdgeId,
  createUniqueNodeId,
  documentToCanvasState,
} from "./adapters";

const NOW = "2026-07-19T12:00:00.000Z";
const LATER = "2026-07-19T13:00:00.000Z";

function fixtureDocument(withPositions: boolean): ArchitectureDocument {
  return parseArchitectureDocument({
    schemaVersion: "1.0",
    id: "doc-1",
    projectId: "project-1",
    name: "Fixture",
    description: "A fixture document",
    createdAt: NOW,
    updatedAt: NOW,
    source: { kind: "generated", label: "Generated by test" },
    assumptions: [{ id: "mau", label: "MAU", value: "10k" }],
    groups: [
      { id: "edge", label: "Edge" },
      { id: "data", label: "Data" },
    ],
    nodes: [
      {
        id: "gateway",
        name: "api-gateway",
        category: "Gateway",
        groupId: "edge",
        iconId: "aws.api-gateway",
        ...(withPositions && { position: { x: 100, y: 200 } }),
      },
      {
        id: "db",
        name: "postgresql",
        category: "Database",
        groupId: "data",
        meta: "conn 82/300",
        ...(withPositions && { position: { x: 400, y: 200 } }),
      },
      { id: "misc", name: "sidecar", category: "Utility", planned: true },
    ],
    edges: [{ id: "gateway--db--data", source: "gateway", target: "db", kind: "data" }],
    metadata: { generator: "test" },
  });
}

describe("documentToCanvasState", () => {
  it("maps nodes and edges with persisted positions", () => {
    const state = documentToCanvasState(fixtureDocument(true));
    expect(state.nodes).toHaveLength(3);
    expect(state.nodes[0]?.position).toEqual({ x: 100, y: 200 });
    expect(state.nodes[0]?.data.name).toBe("api-gateway");
    expect(state.nodes[0]?.data.iconId).toBe("aws.api-gateway");
    expect(state.edges[0]?.data?.kind).toBe("data");
    expect(state.edges[0]?.type).toBe("architecture");
  });

  it("assigns deterministic fallback positions when the document has none", () => {
    const first = documentToCanvasState(fixtureDocument(false));
    const second = documentToCanvasState(fixtureDocument(false));
    expect(first.nodes.map((node) => node.position)).toEqual(
      second.nodes.map((node) => node.position),
    );
    // Directed dependencies flow left-to-right.
    const gateway = first.nodes.find((node) => node.id === "gateway");
    const db = first.nodes.find((node) => node.id === "db");
    expect(db !== undefined && gateway !== undefined && db.position.x > gateway.position.x).toBe(
      true,
    );
  });

  it("does not mutate the source document", () => {
    const document = fixtureDocument(false);
    Object.freeze(document);
    Object.freeze(document.nodes);
    expect(() => documentToCanvasState(document)).not.toThrow();
    expect(document.nodes[0]?.position).toBeUndefined();
  });
});

describe("computeArchitectureAwareLayout", () => {
  it("preserves existing user positions by default", () => {
    const document = fixtureDocument(true);
    const layout = computeArchitectureAwareLayout(document);
    expect(layout.get("gateway")).toEqual({ x: 100, y: 200 });
  });

  it("can produce a full deterministic preview layout", () => {
    const document = fixtureDocument(true);
    const first = computeArchitectureAwareLayout(document, { preserveExistingPositions: false });
    const second = computeArchitectureAwareLayout(document, { preserveExistingPositions: false });
    expect([...first.entries()]).toEqual([...second.entries()]);
    expect(first.get("db")?.x).toBeGreaterThan(first.get("gateway")?.x ?? 0);
  });
});

describe("canvasStateToDocument", () => {
  it("round-trips a document while updating positions and timestamps", () => {
    const previous = fixtureDocument(true);
    const state = documentToCanvasState(previous);
    const moved = state.nodes.map((node) =>
      node.id === "gateway" ? { ...node, position: { x: 123.7, y: 456.2 } } : node,
    );
    const next = canvasStateToDocument(previous, moved, state.edges, LATER);

    expect(() => parseArchitectureDocument(next)).not.toThrow();
    expect(next.updatedAt).toBe(LATER);
    expect(next.createdAt).toBe(previous.createdAt);
    expect(next.nodes.find((node) => node.id === "gateway")?.position).toEqual({ x: 124, y: 456 });
    expect(next.nodes.find((node) => node.id === "gateway")?.iconId).toBe("aws.api-gateway");
    expect(next.nodes.find((node) => node.id === "db")?.meta).toBe("conn 82/300");
    expect(next.assumptions).toEqual(previous.assumptions);
    expect(next.groups).toEqual(previous.groups);
    expect(next.metadata).toEqual(previous.metadata);
  });

  it("strips React Flow runtime state from persistence", () => {
    const previous = fixtureDocument(true);
    const state = documentToCanvasState(previous);
    const noisy = state.nodes.map((node) => ({
      ...node,
      selected: true,
      dragging: true,
      measured: { width: 224, height: 96 },
    }));
    const next = canvasStateToDocument(previous, noisy, state.edges, LATER);
    for (const node of next.nodes) {
      expect(node).not.toHaveProperty("selected");
      expect(node).not.toHaveProperty("dragging");
      expect(node).not.toHaveProperty("measured");
    }
  });

  it("never mutates its inputs", () => {
    const previous = fixtureDocument(true);
    const state = documentToCanvasState(previous);
    Object.freeze(previous);
    Object.freeze(state.nodes);
    Object.freeze(state.edges);
    expect(() => canvasStateToDocument(previous, state.nodes, state.edges, LATER)).not.toThrow();
  });
});

describe("id helpers", () => {
  it("creates unique slugged node ids", () => {
    const existing = new Set(["new-service", "new-service-2"]);
    expect(createUniqueNodeId("New Service!", existing)).toBe("new-service-3");
    expect(createUniqueNodeId("Fresh", existing)).toBe("fresh");
  });

  it("creates unique edge ids", () => {
    const existing = new Set(["a--b--sync"]);
    expect(createUniqueEdgeId("a", "b", "sync", existing)).toBe("a--b--sync-2");
    expect(createUniqueEdgeId("a", "b", "data", existing)).toBe("a--b--data");
  });
});
