import {
  ARCHITECTURE_SCHEMA_VERSION,
  parseArchitectureDocument,
  type ArchitectureDocument,
} from "@axon/diagram-schema";

import { type GeneratedArchitectureDraft } from "./draft-schema";
import { assignPositions } from "./layout";
import { slugifyKey } from "./normalize-draft";

export interface BuildDocumentInput {
  /** A normalized draft (see normalizeDraft). */
  draft: GeneratedArchitectureDraft;
  /** AXON-owned identity and provenance — never model output. */
  documentId: string;
  projectId: string;
  createdAt: string;
  updatedAt: string;
  prompt: string;
  providerId: string;
}

/**
 * Deterministic conversion of a validated draft into a persisted document.
 * AXON assigns ids, timestamps, positions, provenance, and schema version;
 * the result is re-validated against the canonical schema before returning.
 */
export function buildArchitectureDocument(input: BuildDocumentInput): ArchitectureDocument {
  const { draft } = input;
  const positions = assignPositions(draft);

  return parseArchitectureDocument({
    schemaVersion: ARCHITECTURE_SCHEMA_VERSION,
    id: input.documentId,
    projectId: input.projectId,
    name: draft.name,
    description: draft.summary ?? `Generated from prompt: ${input.prompt.slice(0, 240)}`,
    createdAt: input.createdAt,
    updatedAt: input.updatedAt,
    source: { kind: "generated", label: `Generated by ${input.providerId}` },
    assumptions: draft.assumptions.map((assumption, index) => ({
      id: `${slugifyKey(assumption.label)}-${index}`,
      label: assumption.label,
      value: assumption.value,
    })),
    groups: draft.groups.map((group) => ({ id: group.key, label: group.label })),
    nodes: draft.nodes.map((node) => ({
      id: node.key,
      name: node.name,
      category: node.category,
      ...(node.groupKey !== undefined && { groupId: node.groupKey }),
      ...(positions.has(node.key) && { position: positions.get(node.key) }),
    })),
    edges: draft.edges.map((edge) => ({
      id: `${edge.sourceKey}--${edge.targetKey}--${edge.kind}`,
      source: edge.sourceKey,
      target: edge.targetKey,
      kind: edge.kind,
    })),
    metadata: {
      generator: "axon-architecture-generation",
      notes: `provider=${input.providerId}`,
    },
  });
}
