import { sql } from "drizzle-orm";
import {
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Server schema. Internal identifiers are UUIDs generated by the database and
 * never derived from client input. Every product-data table carries an
 * `ownerId` so queries can be scoped to the authenticated user — the core
 * defence against insecure direct object reference.
 */

// --- Auth.js core tables (adapter-compatible shape) ---

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("email_verified", { mode: "date" }),
  image: text("image"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => [primaryKey({ columns: [account.provider, account.providerAccountId] })],
);

export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (vt) => [primaryKey({ columns: [vt.identifier, vt.token] })],
);

// --- Private-beta access control ---

/**
 * A single-use invitation. Redeeming one grants the redeemer beta access;
 * signing in alone never does.
 */
export const betaInvites = pgTable("beta_invites", {
  id: uuid("id").defaultRandom().primaryKey(),
  // The redemption code the user enters. Unique and case-normalised by callers.
  code: text("code").notNull().unique(),
  note: text("note"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  redeemedByUserId: uuid("redeemed_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  redeemedAt: timestamp("redeemed_at", { mode: "date" }),
});

export const betaAccess = pgTable("beta_access", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  inviteId: uuid("invite_id").references(() => betaInvites.id, { onDelete: "set null" }),
  grantedAt: timestamp("granted_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Owner-scoped product data ---

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (project) => [uniqueIndex("projects_owner_idx").on(project.ownerId, project.id)],
);

/**
 * The architecture document for a project. `version` backs optimistic
 * concurrency (Checkpoint 2): a write must present the version it read.
 */
export const documents = pgTable("documents", {
  projectId: uuid("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  document: jsonb("document").notNull(),
  version: integer("version").notNull().default(1),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

/** One row per project per artifact kind; the payload is the validated state JSON. */
export const artifacts = pgTable(
  "artifacts",
  {
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // "audit" | "recommendation" | "simulation" | "import"
    kind: text("kind").notNull(),
    payload: jsonb("payload").notNull(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (artifact) => [primaryKey({ columns: [artifact.projectId, artifact.kind] })],
);

// --- Generation quota and feedback ---

/** Rolling generation usage per user per UTC day, for quota + rate limiting. */
export const generationUsage = pgTable(
  "generation_usage",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    day: text("day").notNull(), // YYYY-MM-DD (UTC)
    count: integer("count").notNull().default(0),
    lastRequestAt: timestamp("last_request_at", { mode: "date" }).notNull().defaultNow(),
  },
  (usage) => [primaryKey({ columns: [usage.userId, usage.day] })],
);

export const feedback = pgTable("feedback", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  category: text("category").notNull(),
  message: text("message").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

export const ARTIFACT_KINDS = ["audit", "recommendation", "simulation", "import"] as const;
export type ArtifactKind = (typeof ARTIFACT_KINDS)[number];

/** Marker used by the migration runner to confirm the schema is present. */
export const SCHEMA_READY = sql`select 1`;
