import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Server schema. Internal identifiers are UUIDs generated by the database and
 * never derived from client input. Every product-data table carries an
 * `ownerId` so queries can be scoped to the authenticated user — the core
 * defence against insecure direct object reference.
 */

// --- Auth.js core tables (adapter-compatible shape) ---

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("email_verified", { mode: "date" }),
  image: text("image"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => [primaryKey({ columns: [account.provider, account.providerAccountId] })],
);

export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (vt) => [primaryKey({ columns: [vt.identifier, vt.token] })],
);

// --- Private-beta access control ---

/**
 * A single-use invitation. Redeeming one grants the redeemer beta access;
 * signing in alone never does.
 */
export const betaInvites = pgTable("beta_invites", {
  id: uuid("id").defaultRandom().primaryKey(),
  // Only the SHA-256 hash of the redemption token is stored — never the raw
  // token. The raw token is shown once at creation and cannot be recovered.
  tokenHash: text("token_hash").notNull().unique(),
  // Optional email the invite is restricted to (lower-cased). When set, only a
  // session whose email matches may redeem it.
  email: text("email"),
  // Optional expiry. When set, redemption after this instant fails safely.
  expiresAt: timestamp("expires_at", { mode: "date" }),
  note: text("note"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  redeemedByUserId: uuid("redeemed_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  redeemedAt: timestamp("redeemed_at", { mode: "date" }),
});

export const betaAccess = pgTable("beta_access", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  inviteId: uuid("invite_id").references(() => betaInvites.id, { onDelete: "set null" }),
  grantedAt: timestamp("granted_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Owner-scoped product data ---

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (project) => [uniqueIndex("projects_owner_idx").on(project.ownerId, project.id)],
);

/**
 * The architecture document for a project. `version` backs optimistic
 * concurrency (Checkpoint 2): a write must present the version it read.
 */
export const documents = pgTable("documents", {
  projectId: uuid("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  document: jsonb("document").notNull(),
  version: integer("version").notNull().default(1),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

/** One row per project per artifact kind; the payload is the validated state JSON. */
export const artifacts = pgTable(
  "artifacts",
  {
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // "audit" | "recommendation" | "simulation" | "import"
    kind: text("kind").notNull(),
    payload: jsonb("payload").notNull(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (artifact) => [primaryKey({ columns: [artifact.projectId, artifact.kind] })],
);

// --- Generation quota and feedback ---

/** Rolling generation usage per user per UTC day, for quota + rate limiting. */
export const generationUsage = pgTable(
  "generation_usage",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    day: text("day").notNull(), // YYYY-MM-DD (UTC)
    count: integer("count").notNull().default(0),
    lastRequestAt: timestamp("last_request_at", { mode: "date" }).notNull().defaultNow(),
  },
  (usage) => [primaryKey({ columns: [usage.userId, usage.day] })],
);

export const feedback = pgTable("feedback", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  category: text("category").notNull(),
  message: text("message").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- GitHub repository intelligence (Checkpoint 5) ---
//
// A separate GitHub App (not the identity OAuth App) grants read-only access to
// repositories the user explicitly selects. These tables store only safe
// references and metadata: installation access tokens are minted server-side
// per request and never persisted, and the App private key is never stored here.

/**
 * Short-lived, single-use state for the GitHub App installation redirect. The
 * signed state token carries this row's id; redemption at the callback claims
 * the row atomically (consumed_at) so a replayed callback fails safely.
 */
export const githubInstallStates = pgTable("github_install_states", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expiresAt: timestamp("expires_at", { mode: "date" }).notNull(),
  consumedAt: timestamp("consumed_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** A GitHub App installation the user has connected and bound to their account. */
export const githubInstallations = pgTable(
  "github_installations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // GitHub's numeric installation id — an identifier, never a token.
    installationId: bigint("installation_id", { mode: "number" }).notNull(),
    accountId: bigint("account_id", { mode: "number" }).notNull(),
    accountLogin: text("account_login").notNull(),
    accountType: text("account_type").notNull(), // "User" | "Organization"
    status: text("status").notNull().default("connected"),
    permissionsSnapshot: jsonb("permissions_snapshot"),
    connectedAt: timestamp("connected_at", { mode: "date" }).notNull().defaultNow(),
    lastVerifiedAt: timestamp("last_verified_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  // Globally unique: an installation binds to exactly one account, so a second
  // user can never claim one already linked elsewhere.
  (t) => [uniqueIndex("github_installations_installation_idx").on(t.installationId)],
);

/** A repository granted to an installation and connected for analysis. */
export const connectedRepositories = pgTable(
  "connected_repositories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    installationConnectionId: uuid("installation_connection_id")
      .notNull()
      .references(() => githubInstallations.id, { onDelete: "cascade" }),
    // Stable GitHub numeric repository id — the remote identity, never a name.
    repoGithubId: bigint("repo_github_id", { mode: "number" }).notNull(),
    ownerLogin: text("owner_login").notNull(),
    name: text("name").notNull(),
    fullName: text("full_name").notNull(),
    defaultBranch: text("default_branch").notNull(),
    visibility: text("visibility").notNull(), // "public" | "private"
    archived: boolean("archived").notNull().default(false),
    url: text("url").notNull(),
    lastAnalyzedSha: text("last_analyzed_sha"),
    lastSyncStatus: text("last_sync_status"),
    lastSyncAt: timestamp("last_sync_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("connected_repositories_owner_repo_idx").on(t.ownerId, t.repoGithubId)],
);

/** One manual static-analysis run against a repository at a specific commit. */
export const repositoryAnalysisRuns = pgTable("repository_analysis_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  repositoryConnectionId: uuid("repository_connection_id")
    .notNull()
    .references(() => connectedRepositories.id, { onDelete: "cascade" }),
  requestedByUserId: uuid("requested_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  commitSha: text("commit_sha").notNull(),
  status: text("status").notNull().default("pending"), // pending|running|succeeded|failed
  startedAt: timestamp("started_at", { mode: "date" }),
  completedAt: timestamp("completed_at", { mode: "date" }),
  supportedFileCount: integer("supported_file_count").notNull().default(0),
  skippedFileCount: integer("skipped_file_count").notNull().default(0),
  evidenceCount: integer("evidence_count").notNull().default(0),
  proposalId: uuid("proposal_id"),
  failureCode: text("failure_code"),
  failureSummary: text("failure_summary"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** Structured, deterministic evidence extracted from a repository file. */
export const repositoryEvidence = pgTable("repository_evidence", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  analysisRunId: uuid("analysis_run_id")
    .notNull()
    .references(() => repositoryAnalysisRuns.id, { onDelete: "cascade" }),
  repositoryConnectionId: uuid("repository_connection_id")
    .notNull()
    .references(() => connectedRepositories.id, { onDelete: "cascade" }),
  commitSha: text("commit_sha").notNull(),
  filePath: text("file_path").notNull(),
  startLine: integer("start_line"),
  endLine: integer("end_line"),
  evidenceType: text("evidence_type").notNull(),
  extractor: text("extractor").notNull(),
  // A safe, redacted excerpt — never a secret value or full file.
  excerpt: text("excerpt"),
  fact: jsonb("fact").notNull(),
  confidence: text("confidence").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** A reviewable architecture proposal derived from repository evidence. */
export const architectureProposals = pgTable("architecture_proposals", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  // Nullable until the user applies the proposal to a specific project.
  projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
  repositoryConnectionId: uuid("repository_connection_id")
    .notNull()
    .references(() => connectedRepositories.id, { onDelete: "cascade" }),
  analysisRunId: uuid("analysis_run_id").references(() => repositoryAnalysisRuns.id, {
    onDelete: "set null",
  }),
  sourceCommitSha: text("source_commit_sha").notNull(),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  proposal: jsonb("proposal").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Architecture Snapshots and Drift (Checkpoint 7) ---

/** Immutable architecture snapshot recording exact document payload, version, hash, and reason. */
export const architectureSnapshots = pgTable("architecture_snapshots", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  documentVersion: integer("document_version").notNull(),
  payload: jsonb("payload").notNull(),
  creationReason: text("creation_reason").notNull(),
  createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
  previousSnapshotId: uuid("previous_snapshot_id"),
  semanticHash: text("semantic_hash").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** Detected architectural drift between intended, repository, IaC, and proposal states. */
export const architectureDrifts = pgTable("architecture_drifts", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  baseSnapshotId: uuid("base_snapshot_id")
    .notNull()
    .references(() => architectureSnapshots.id, { onDelete: "cascade" }),
  comparedSnapshotId: uuid("compared_snapshot_id").references(() => architectureSnapshots.id, { onDelete: "cascade" }),
  driftCategory: text("drift_category").notNull(),
  status: text("status").notNull().default("detected"),
  semanticChanges: jsonb("semantic_changes").notNull(),
  severity: text("severity").notNull(),
  confidence: text("confidence").notNull(),
  userDecision: text("user_decision"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  resolvedAt: timestamp("resolved_at", { mode: "date" }),
});

// --- GitHub Pull Request Architecture Reviews (Checkpoint 8) ---

/** Pull-request static architecture analysis run for a connected repository. */
export const githubPrAnalysisRuns = pgTable("github_pr_analysis_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  repositoryConnectionId: uuid("repository_connection_id")
    .notNull()
    .references(() => connectedRepositories.id, { onDelete: "cascade" }),
  prNumber: integer("pr_number").notNull(),
  prTitle: text("pr_title").notNull(),
  prAuthor: text("pr_author").notNull(),
  headSha: text("head_sha").notNull(),
  baseSha: text("base_sha").notNull(),
  status: text("status").notNull().default("pending"),
  architectureRisk: text("architecture_risk").notNull().default("none"),
  proposalId: uuid("proposal_id").references(() => architectureProposals.id, { onDelete: "set null" }),
  impactSummary: jsonb("impact_summary").notNull(),
  commentPostedAt: timestamp("comment_posted_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Read-only Cloud Discovery (Checkpoint 10) ---

/** A read-only AWS or GCP connection (IAM role ARN or Service Account). */
export const cloudConnections = pgTable("cloud_connections", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(), // "aws" | "gcp"
  accountOrProjectId: text("account_or_project_id").notNull(),
  roleArnOrServiceAccount: text("role_arn_or_service_account").notNull(),
  status: text("status").notNull().default("connected"),
  lastDiscoveredAt: timestamp("last_discovered_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** A read-only cloud discovery execution run. */
export const cloudDiscoveryRuns = pgTable("cloud_discovery_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  connectionId: uuid("connection_id")
    .notNull()
    .references(() => cloudConnections.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("pending"),
  discoveredAssetCount: integer("discovered_asset_count").notNull().default(0),
  matchedAssetCount: integer("matched_asset_count").notNull().default(0),
  unmanagedAssetCount: integer("unmanaged_asset_count").notNull().default(0),
  proposalId: uuid("proposal_id").references(() => architectureProposals.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Runtime Telemetry & Calibrated Simulation (Checkpoint 11) ---

/** A runtime telemetry metrics source (Prometheus, CloudWatch, Datadog, OTLP). */
export const telemetrySources = pgTable("telemetry_sources", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(), // "prometheus" | "cloudwatch" | "datadog" | "opentelemetry"
  name: text("name").notNull(),
  endpointUrl: text("endpoint_url").notNull(),
  status: text("status").notNull().default("connected"),
  lastSampledAt: timestamp("last_sampled_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** Ingested telemetry metric samples. */
export const telemetryMetrics = pgTable("telemetry_metrics", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  telemetrySourceId: uuid("telemetry_source_id")
    .notNull()
    .references(() => telemetrySources.id, { onDelete: "cascade" }),
  componentId: text("component_id").notNull(),
  metricName: text("metric_name").notNull(),
  value: doublePrecision("value").notNull(),
  unit: text("unit").notNull(),
  sampledAt: timestamp("sampled_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Controlled Infrastructure Pull Requests (Checkpoint 12) ---

/** Record of generated Terraform/Kubernetes PRs submitted to GitHub. */
export const generatedInfrastructurePrs = pgTable("generated_infrastructure_prs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  repositoryConnectionId: uuid("repository_connection_id")
    .notNull()
    .references(() => connectedRepositories.id, { onDelete: "cascade" }),
  proposalId: uuid("proposal_id")
    .notNull()
    .references(() => architectureProposals.id, { onDelete: "cascade" }),
  prNumber: integer("pr_number").notNull(),
  prUrl: text("pr_url").notNull(),
  branchName: text("branch_name").notNull(),
  targetBranch: text("target_branch").notNull().default("main"),
  status: text("status").notNull().default("open"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- GitHub webhook processing (Checkpoint 8) ---

/**
 * Every accepted GitHub webhook delivery. The GitHub delivery id is unique, so a
 * replayed or duplicated delivery is idempotently ignored. Only safe metadata is
 * stored — never the payload, secret, or any source content.
 */
export const githubWebhookEvents = pgTable("github_webhook_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  // GitHub's X-GitHub-Delivery — the dedup / replay-protection key.
  deliveryId: text("delivery_id").notNull().unique(),
  eventType: text("event_type").notNull(),
  installationId: bigint("installation_id", { mode: "number" }),
  repositoryGithubId: bigint("repository_github_id", { mode: "number" }),
  prNumber: integer("pr_number"),
  beforeSha: text("before_sha"),
  afterSha: text("after_sha"),
  // Resolved from the installation → connected repo; null when unowned/ignored.
  ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
  status: text("status").notNull().default("received"), // received|queued|processed|ignored|failed
  failureCode: text("failure_code"),
  receivedAt: timestamp("received_at", { mode: "date" }).notNull().defaultNow(),
  processedAt: timestamp("processed_at", { mode: "date" }),
});

/**
 * PostgreSQL-backed background jobs. A job is claimed with a lease, retried up to
 * a bound, and moved to a dead-letter state on exhaustion. `idempotencyKey` (e.g.
 * the webhook delivery id) prevents duplicate work from duplicate deliveries.
 */
export const backgroundJobs = pgTable("background_jobs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id").references(() => users.id, { onDelete: "cascade" }),
  kind: text("kind").notNull(),
  idempotencyKey: text("idempotency_key").notNull().unique(),
  payload: jsonb("payload").notNull(),
  status: text("status").notNull().default("pending"), // pending|leased|succeeded|failed|dead
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(5),
  leaseExpiresAt: timestamp("lease_expires_at", { mode: "date" }),
  lastError: text("last_error"),
  progress: integer("progress").notNull().default(0),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

export const ARTIFACT_KINDS = ["audit", "recommendation", "simulation", "import"] as const;
export type ArtifactKind = (typeof ARTIFACT_KINDS)[number];

// --- Local Agent Connections (Checkpoint 13) ---

export const localAgentConnections = pgTable("local_agent_connections", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  agentName: text("agent_name").notNull(),
  machineLabel: text("machine_label").notNull(),
  tokenHash: text("token_hash").notNull(),
  workspaceScope: text("workspace_scope").notNull(),
  allowedCapabilities: jsonb("allowed_capabilities").notNull().default(sql`'[]'::jsonb`),
  lastConnectedAt: timestamp("last_connected_at", { mode: "date" }),
  revokedAt: timestamp("revoked_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

export const localEvidenceSyncRuns = pgTable("local_evidence_sync_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  agentConnectionId: uuid("agent_connection_id").notNull().references(() => localAgentConnections.id, { onDelete: "cascade" }),
  projectId: uuid("project_id"),
  evidenceCount: integer("evidence_count").notNull().default(0),
  componentCount: integer("component_count").notNull().default(0),
  status: text("status").notNull().default("pending"), // pending|reviewing|synced|rejected
  syncedAt: timestamp("synced_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

/** Marker used by the migration runner to confirm the schema is present. */
export const SCHEMA_READY = sql`select 1`;
