import { expect, test } from "@playwright/test";

test("creates a sample project and opens its persisted workspace", async ({ page }) => {
  await page.goto("/projects");
  await expect(page.getByText("No projects yet.")).toBeVisible();

  await page.getByRole("link", { name: "New Project" }).first().click();
  await expect(page).toHaveURL(/\/projects\/new/);

  await page.getByLabel("Project name").fill("Beta walkthrough");
  await page.getByRole("radio", { name: /Sample architecture/ }).check();
  await page.getByRole("button", { name: "Create Project" }).click();

  await expect(page).toHaveURL(/\/projects\/[0-9a-f-]{36}$/);
  await expect(page.getByRole("heading", { name: "Beta walkthrough" })).toBeVisible();
  await expect(page.locator(".react-flow__node", { hasText: "postgresql" })).toBeVisible();
  await expect(page.getByText("Sample: SaaS reference architecture")).toBeVisible();

  // Local-first: the document survives a reload.
  await page.reload();
  await expect(page.getByRole("heading", { name: "Beta walkthrough" })).toBeVisible();

  // And appears in the project list.
  await page.goto("/projects");
  await expect(page.getByRole("link", { name: "Beta walkthrough" })).toBeVisible();
});

test("landing primary CTA leads to real project creation", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: "Build Your First Architecture" }).click();
  await expect(page).toHaveURL(/\/projects\/new/);
  await expect(page.getByLabel("Project name")).toBeVisible();
});

test("generates an architecture from a prompt in a blank workspace", async ({ page }) => {
  await page.goto("/projects/new");
  await page.getByLabel("Project name").fill("Prompt start");
  await page.getByRole("radio", { name: /^Blank/ }).check();
  await page.getByRole("button", { name: "Create Project" }).click();
  await expect(page.getByRole("heading", { name: "Prompt start" })).toBeVisible();

  // Blank documents offer generation instead of a canvas.
  await page
    .getByLabel("Describe the system")
    .fill("A SaaS platform with billing, background jobs and file exports");
  await page.getByRole("button", { name: "Generate Architecture" }).click();

  // Offline mode is pinned for e2e; the result is labeled honestly.
  await expect(page.locator(".react-flow__node", { hasText: "payments-service" })).toBeVisible({
    timeout: 15_000,
  });
  await expect(page.locator(".react-flow__node", { hasText: "worker-pool" })).toBeVisible();
  await expect(page.getByText(/Generated by offline-template/)).toBeVisible();

  // Local-first: the generated document survives a reload.
  await page.reload();
  await expect(page.locator(".react-flow__node", { hasText: "payments-service" })).toBeVisible();
});
