import { type ArchitectureProposal, type ProposalComponent } from "../schemas";

export interface GeneratedIacFiles {
  terraformHcl: string;
  kubernetesYaml: string;
  files: { path: string; content: string }[];
}

/**
 * Converts an ArchitectureProposal into declarative Terraform HCL and Kubernetes YAML files.
 */
export function generateInfrastructureCode(proposal: ArchitectureProposal): GeneratedIacFiles {
  const terraformHclLines: string[] = [
    `# Generated by AXON Architecture Intelligence`,
    `# Proposal ID: ${proposal.sourceCommitSha}`,
    `# Date: ${proposal.createdAt}`,
    ``,
    `terraform {`,
    `  required_version = ">= 1.5.0"`,
    `  required_providers {`,
    `    aws = {`,
    `      source  = "hashicorp/aws"`,
    `      version = "~> 5.0"`,
    `    }`,
    `    google = {`,
    `      source  = "hashicorp/google"`,
    `      version = "~> 5.0"`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ];

  const k8sYamlDocs: string[] = [
    `# Generated by AXON Architecture Intelligence`,
    `# Proposal ID: ${proposal.sourceCommitSha}`,
  ];

  for (const comp of proposal.components) {
    appendComponentTerraformHcl(comp, terraformHclLines);
    appendComponentKubernetesYaml(comp, k8sYamlDocs);
  }

  const terraformHcl = terraformHclLines.join("\n");
  const kubernetesYaml = k8sYamlDocs.join("\n---\n");

  return {
    terraformHcl,
    kubernetesYaml,
    files: [
      { path: "terraform/main.tf", content: terraformHcl },
      { path: "k8s/deployment.yaml", content: kubernetesYaml },
    ],
  };
}

function appendComponentTerraformHcl(comp: ProposalComponent, lines: string[]): void {
  const safeName = comp.id.replace(/[^a-zA-Z0-9_]/g, "_");
  const tech = comp.technology || "aws_instance";

  lines.push(`resource "${tech}" "${safeName}" {`);
  lines.push(`  # Component: ${comp.name}`);
  lines.push(`  # Category: ${comp.category}`);

  if (tech.startsWith("aws_")) {
    lines.push(`  tags = {`);
    lines.push(`    Name        = "${comp.name}"`);
    lines.push(`    ManagedBy   = "AXON"`);
    lines.push(`  }`);
  } else if (tech.startsWith("google_")) {
    lines.push(`  name = "${safeName.toLowerCase()}"`);
    lines.push(`  labels = {`);
    lines.push(`    managed_by = "axon"`);
    lines.push(`  }`);
  }

  lines.push(`}`);
  lines.push(``);
}

function appendComponentKubernetesYaml(comp: ProposalComponent, docs: string[]): void {
  const safeName = comp.name.toLowerCase().replace(/[^a-z0-9-]/g, "-");

  if (comp.category === "compute" || comp.category === "service" || comp.category === "worker") {
    docs.push(`apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${safeName}
  labels:
    app.kubernetes.io/name: ${safeName}
    app.kubernetes.io/managed-by: axon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${safeName}
  template:
    metadata:
      labels:
        app: ${safeName}
    spec:
      containers:
        - name: ${safeName}
          image: ${safeName}:latest
          ports:
            - containerPort: 8080`);
  }
}
