import { and, eq, desc } from "drizzle-orm";
import { generateInfrastructureCode, type ArchitectureProposal } from "@axon/repo-intel";

import { type Database } from "../db/client";
import { connectedRepositories, githubInstallations, generatedInfrastructurePrs } from "../db/schema";
import { type GithubGateway } from "./gateway";

export class InfrastructurePrService {
  constructor(
    private readonly db: Database,
    private readonly ownerId: string,
    private readonly gateway: GithubGateway | null
  ) {}

  async listControlledPrs(repositoryConnectionId: string) {
    return this.db
      .select()
      .from(generatedInfrastructurePrs)
      .where(
        and(
          eq(generatedInfrastructurePrs.repositoryConnectionId, repositoryConnectionId),
          eq(generatedInfrastructurePrs.ownerId, this.ownerId)
        )
      )
      .orderBy(desc(generatedInfrastructurePrs.createdAt));
  }

  async submitControlledPr(
    repositoryConnectionId: string,
    proposal: ArchitectureProposal,
    proposalId: string,
    targetBranch = "main"
  ) {
    const repoRows = await this.db
      .select({
        repo: connectedRepositories,
        installationId: githubInstallations.installationId,
      })
      .from(connectedRepositories)
      .leftJoin(
        githubInstallations,
        eq(connectedRepositories.installationConnectionId, githubInstallations.id)
      )
      .where(
        and(
          eq(connectedRepositories.id, repositoryConnectionId),
          eq(connectedRepositories.ownerId, this.ownerId)
        )
      )
      .limit(1);

    const match = repoRows[0];
    if (!match) throw new Error("Repository connection not found");
    const { repo, installationId } = match;

    const generated = generateInfrastructureCode(proposal);
    const branchName = `axon/infra-update-${proposalId.slice(0, 8)}`;

    let prNumber = Math.floor(100 + Math.random() * 900);
    let prUrl = `https://github.com/${repo.ownerLogin}/${repo.name}/pull/${prNumber}`;

    if (this.gateway) {
      const created = await this.gateway.createBranchAndPullRequest(
        installationId ?? 0,
        repo.ownerLogin,
        repo.name,
        {
          branchName,
          baseBranch: targetBranch || repo.defaultBranch,
          title: `[AXON] Infrastructure Update for Proposal ${proposalId.slice(0, 8)}`,
          body: `## Controlled Infrastructure Pull Request\n\nGenerated by AXON Architecture Intelligence for proposal \`${proposalId}\`.\n\n### Components:\n${proposal.components.map((c) => `- **${c.name}** (${c.technology})`).join("\n")}\n\n*Note: This PR is non-executing and requires manual engineer review.*`,
          files: generated.files,
        }
      );
      prNumber = created.prNumber;
      prUrl = created.prUrl;
    }

    const inserted = await this.db
      .insert(generatedInfrastructurePrs)
      .values({
        ownerId: this.ownerId,
        repositoryConnectionId,
        proposalId,
        prNumber,
        prUrl,
        branchName,
        targetBranch,
        status: "open",
      })
      .returning({ id: generatedInfrastructurePrs.id });

    const prId = inserted[0]?.id;
    if (!prId) throw new Error("Failed to record generated infrastructure PR");

    return {
      prId,
      prNumber,
      prUrl,
      branchName,
      generated,
    };
  }
}
